### PR TITLE
Some updates of dish part

### PR DESCRIPTION
**Pull request by BotBw**

### CODE REVIEW

**Review by Lim-Shi-Han — APPROVED** [review]
lgtm, logInfo is a good idea, maybe we can consider creating a logger class

**Comment by darylhjd** [comment]
dont merge yet bah, until we settle the tests first.

**Comment by Lim-Shi-Han** [comment]
> dont merge yet bah, until we settle the tests first.

but then the test that is failing now is the ordermanagertest I think so should be ok? Although the tests that pass might also need some adjustments to make sense

**Comment by darylhjd** [comment]
why not make the logger a static variable of the Controller class?

**Comment by BotBw** [comment]
> why not make the logger a static variable of the Controller class? then the logInfo (and logError etc... i cant rmbr all the levels of logging) methods can go into the Controller class as well.
> 
> if we want to show the class name, i think java has a way of getting that.

Yup log print the class name and the function calling it. I don't want to modify others' code (in case something goes wrong) so I added a logger here. 
And I prefer creating a global Logger class as Shi Han said so I close this pr first.

**Pull request closed without merging**
