### PR TITLE
Fix Manager implementation

### PR DESCRIPTION
**Pull request by darylhjd**

### CODE REVIEW

**Review by Lim-Shi-Han — COMMENTED** [review]
But that means if the user terminate the programme then it won't safe though

**Comment by darylhjd** [comment]
> But that means if the user terminate the programme then it won't safe though

wdym

**Comment by Lim-Shi-Han** [comment]
> 

As in like when the user inputs '-' to terminate the program the new data won't be saved... So is that by design or what

**Comment by darylhjd** [comment]
> > 
> 
> As in like when the user inputs '-' to terminate the program the new data won't be saved... So is that by design or what

hmm it wont save meh. when i in the dish menu and i enter "-" it will save. u try

**Comment by Lim-Shi-Han** [comment]
Oh ok it works yup

**Review by Lim-Shi-Han — APPROVED** [review]
lgtm

**Pull request merged**
