### PR TITLE
Add class for getting input from user.

### PR DESCRIPTION
**Pull request by darylhjd**

### CODE REVIEW

**Comment by darylhjd** [comment]
@wang1351 @Lim-Shi-Han @BotBw will need yall to update your controllers to make use of this new way of getting input.

**Comment by darylhjd** [comment]
the tests will fail now, but i will merge anyway after a review, but yall need to change the controllers after that

**Comment by BotBw** [comment]
> @wang1351 @Lim-Shi-Han @BotBw will need yall to update your controllers to make use of this new way of getting input.

noticed

**Comment by darylhjd** [comment]
i will update this to push to a new branch called `new_input`, so yall can update your controllers and push the changes to that new branch, in case something goes wrong in `master` branch

**Pull request merged**
